SPOOL dropdatabase
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 200
SET WRAP OFF

DROP TABLE APPLIES PURGE;
DROP TABLE LNEEDED PURGE;
DROP TABLE LPOSSESSED PURGE;
DROP TABLE EMPLBY PURGE;
DROP TABLE COMPANY PURGE;
DROP TABLE APPLICANT PURGE;
DROP TABLE LANGUAGE PURGE;
DROP TABLE POSITION PURGE;

PROMPT Done.

SPOOL OFF